-- MySQL Script generated by MySQL Workbench
-- lun 20 may 2019 05:25:21 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`rbs_bike`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rbs_bike` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rbs_bike` (
  `bke_id` INT(11) NOT NULL AUTO_INCREMENT,
  `bke_serial` VARCHAR(45) NULL,
  PRIMARY KEY (`bke_id`),
  UNIQUE INDEX `bke_serial_UNIQUE` (`bke_serial` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rbs_rent_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rbs_rent_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rbs_rent_type` (
  `rtt_id` INT(11) NOT NULL AUTO_INCREMENT,
  `rtt_name` VARCHAR(45) NOT NULL,
  `rtt_description` VARCHAR(45) NULL,
  PRIMARY KEY (`rtt_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rbs_promotion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rbs_promotion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rbs_promotion` (
  `pro_id` TINYINT(5) NOT NULL AUTO_INCREMENT,
  `pro_name` VARCHAR(32) NOT NULL,
  `pro_description` VARCHAR(45) NULL,
  `pro_discount` DECIMAL(2,2) NOT NULL,
  `pro_bike_min` TINYINT(2) NOT NULL,
  `pro_bike_max` TINYINT(2) NOT NULL,
  PRIMARY KEY (`pro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rbs_currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rbs_currency` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rbs_currency` (
  `ccy_id` INT(3) NOT NULL AUTO_INCREMENT,
  `ccy_isocode` VARCHAR(45) NOT NULL,
  `ccy_name` VARCHAR(45) NOT NULL,
  `rbs_symbol` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`ccy_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rbs_rent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rbs_rent` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rbs_rent` (
  `rnt_id` INT(11) NOT NULL AUTO_INCREMENT,
  `rnt_price` DECIMAL(10,4) NOT NULL,
  `rbs_currency_ccy_id` INT(3) NOT NULL,
  `rbs_rent_type_rtt_id` INT(11) NOT NULL,
  PRIMARY KEY (`rnt_id`),
  INDEX `fk_rbs_rent_rbs_currency1_idx` (`rbs_currency_ccy_id` ASC),
  INDEX `fk_rbs_rent_rbs_rent_type1_idx` (`rbs_rent_type_rtt_id` ASC),
  CONSTRAINT `fk_rbs_rent_rbs_currency1`
    FOREIGN KEY (`rbs_currency_ccy_id`)
    REFERENCES `mydb`.`rbs_currency` (`ccy_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rbs_rent_rbs_rent_type1`
    FOREIGN KEY (`rbs_rent_type_rtt_id`)
    REFERENCES `mydb`.`rbs_rent_type` (`rtt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rbs_rent_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rbs_rent_detail` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rbs_rent_detail` (
  `rbd_id` INT(11) NOT NULL AUTO_INCREMENT,
  `rtd_bike_bke_id` INT(11) NOT NULL,
  `rtd_cuantity` TINYINT(2) NULL,
  `rtd_start_date` DATETIME NOT NULL DEFAULT NOW(),
  `rtd_end_date` DATETIME NULL,
  `rtd_creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `rbs_update_date` TIMESTAMP NULL,
  `rbs_promotion_pro_id` TINYINT(5) NOT NULL,
  `rbs_bike_bke_id` INT(11) NOT NULL,
  `rbs_rent_rnt_id` INT(11) NOT NULL,
  PRIMARY KEY (`rtd_bike_bke_id`),
  INDEX `fk_rbs_rent_detail_rbs_promotion1_idx` (`rbs_promotion_pro_id` ASC),
  INDEX `fk_rbs_rent_detail_rbs_bike1_idx` (`rbs_bike_bke_id` ASC),
  INDEX `fk_rbs_rent_detail_rbs_rent1_idx` (`rbs_rent_rnt_id` ASC),
  UNIQUE INDEX `rbd_id_UNIQUE` (`rbd_id` ASC),
  CONSTRAINT `fk_rbs_rent_detail_rbs_promotion1`
    FOREIGN KEY (`rbs_promotion_pro_id`)
    REFERENCES `mydb`.`rbs_promotion` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rbs_rent_detail_rbs_bike1`
    FOREIGN KEY (`rbs_bike_bke_id`)
    REFERENCES `mydb`.`rbs_bike` (`bke_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rbs_rent_detail_rbs_rent1`
    FOREIGN KEY (`rbs_rent_rnt_id`)
    REFERENCES `mydb`.`rbs_rent` (`rnt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`rbs_rent_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`rbs_rent_type` (`rtt_id`, `rtt_name`, `rtt_description`) VALUES (1, 'hour', 'Hour');
INSERT INTO `mydb`.`rbs_rent_type` (`rtt_id`, `rtt_name`, `rtt_description`) VALUES (2, 'day', 'Day');
INSERT INTO `mydb`.`rbs_rent_type` (`rtt_id`, `rtt_name`, `rtt_description`) VALUES (3, 'week', 'Week');
INSERT INTO `mydb`.`rbs_rent_type` (`rtt_id`, `rtt_name`, `rtt_description`) VALUES (, DEFAULT, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`rbs_promotion`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`rbs_promotion` (`pro_id`, `pro_name`, `pro_description`, `pro_discount`, `pro_bike_min`, `pro_bike_max`) VALUES (DEFAULT, 'family_rental', 'Family Rental', 0,3, 3, 5);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`rbs_currency`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`rbs_currency` (`ccy_id`, `ccy_isocode`, `ccy_name`, `rbs_symbol`) VALUES (1, 'USD', 'Dollar', '$');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`rbs_rent`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`rbs_rent` (`rnt_id`, `rnt_price`, `rbs_currency_ccy_id`, `rbs_rent_type_rtt_id`) VALUES (DEFAULT, 5, 1, 1);
INSERT INTO `mydb`.`rbs_rent` (`rnt_id`, `rnt_price`, `rbs_currency_ccy_id`, `rbs_rent_type_rtt_id`) VALUES (DEFAULT, 20, 1, 2);
INSERT INTO `mydb`.`rbs_rent` (`rnt_id`, `rnt_price`, `rbs_currency_ccy_id`, `rbs_rent_type_rtt_id`) VALUES (DEFAULT, 60, 1, 3);

COMMIT;

